ToDo/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
    }
}

ToDo/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Models
{
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
    }
}

ToDo/Models/Task.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDo.Models
{
    public class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime? DueDate { get; set; }
        public string Status { get; set; }
    }
}

ToDo/Models/TaskContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace ToDo.Models
{
    public class TaskContext : DbContext
    {
        public DbSet<Task> Tasks { get; set; }
    }
}

ToDo/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ToDo.Models
{
    public class TaskViewModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Description (optional)")]
        public string Description { get; set; }

        [Display(Name = "DueDate (optional)")]
        public DateTime? DueDate { get; set; }

    }
}

ToDo/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDo.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Email { get; set; }
    }
}

ToDo/Models/UserContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace ToDo.Models
{
    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }
    }
}

ToDo/Controllers/AccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ToDo.Models;

namespace Bstow.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {

        public AccountController()
        {
        }


        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login()
        {        
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ReturnUrl = "/";
                UserContext db = new UserContext();
                var UserName = db.Users.Where(i => i.Email == model.Email).FirstOrDefault();
                if (UserName != null)
                {
                    FormsAuthentication.SetAuthCookie(model.Email, false);
                    
                    return Redirect("/");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
        
        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User { Email = model.Email };
                UserContext db = new UserContext();
                try
                {
                    db.Users.Add(user);
                    db.SaveChanges();

                    return Redirect("/Account/Login");
                }
                catch (Exception e)
                {
                    throw e;
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }

}

ToDo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDo.Models;

namespace ToDo.Controllers
{

     
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            UserContext db = new UserContext();

            return View(db.Users.ToList());
        }
    }
}

ToDo/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDo.Models;

namespace ToDo.Controllers
{

     
    public class TaskController : Controller
    {
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                TaskContext db = new TaskContext();
                return View(db.Tasks.ToList());
            }
            else
            {
                return RedirectToAction("/Account/Login");
            }
        }

        public ActionResult Create()
        {
            if (Request.IsAuthenticated)
            {
                return View("Create");
            }
            else
            {
                return RedirectToAction("/Account/Login");
            }
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskViewModel model)
        {
            if (Request.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    var task = new Task { Title = model.Title, Description = model.Description, DueDate = model.DueDate, Status = "In progress" };
                    TaskContext db = new TaskContext();
                    try
                    {
                        db.Tasks.Add(task);
                        db.SaveChanges();

                        return Redirect("/Task/Index");
                    }
                    catch (Exception e)
                    {
                        throw e;
                    }
                }
            }
            

            // If we got this far, something failed, redirect to login
            return RedirectToAction("/Account/Login");
        }

    }
}

ToDo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToDo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToDo/Views/Home/Index.cshtml
@model IEnumerable<ToDo.Models.User>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    @if (Request.IsAuthenticated)
    {
        <p class="lead">You successfully logged in.</p>
        <p class="lead">Continue <a href="/Task/Index">here</a></p>
    }
    else
    {
        <h1>Hi!</h1>
        <p class="lead">You should log in first.</p>
    }
    
</div>

ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ToDo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("ToDoList", "Index", "Task")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ToDo/Views/Task/Create.cshtml
@model ToDo.Models.TaskViewModel
@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "Task", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new ToDo.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @placeholder = "Title" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @placeholder = "Description" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DueDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DueDate, new { @class = "form-control", @placeholder = "mm/dd/yyyy" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDo/Views/Task/Index.cshtml
@model IEnumerable<ToDo.Models.Task>
@{
    ViewBag.Title = "Tasks list";
}
<script type="text/javascript">
    $("#CheckOff").click(function () {
        $.post("demo_test_post.asp",
        {
            name: "Donald Duck",
            city: "Duckburg"
        },
        function (data, status) {
            alert("Data: " + data + "\nStatus: " + status);
        });
    });
</script>

<div class="jumbotron">
    <h1>I should do this list!</h1>
</div>

<div class="row">
    <div class="col-xs-12">
        <a class="btn btn-primary" href="/Task/Create">Add new task</a>
    </div>
</div>
<br/>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-bordered">
            <tr>
                <td>ID</td>
                <td>Title</td>
                <td>Description</td>
                <td>Due Date</td>
                <td>Status</td>
                <td>Actions</td>
            </tr>
            @foreach (ToDo.Models.Task b in Model)
            {
                <tr>
                    <td><p>@b.Id</p></td>
                    <td><p>@b.Title</p></td>
                    <td><p>@b.Description</p></td>
                    <td><p>@b.DueDate</p></td>
                    <td><p>@b.Status</p></td>
                    <td>
                        <a class="btn btn-success" id="CheckOff">Check off</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>